### ISSUE TITLE
Unable to scroll to ids in iframe

### ISSUE THREAD

**Issue by MrPickles2009** [Developmint/vue-next-level-scroll#27]
This scroller works really well on my website but on one of my pages I have an iframe that I would also like to do auto-scrolling in. Is there a way to scroll to targets inside the iframe?

Here is my code currently:

```vue
<template>
    <section>
	<VueNextLevelScroll target='#footer'>
	    <button class="button">go to footer</button>
	</VueNextLevelScroll>
	<iframe src="externalWebsiteUrl"></iframe>
	<footer id="footer">
	    <VueNextLevelScroll>
		<button class="button">go to top</button>
	    </VueNextLevelScroll>
	</footer>
    </section>
</template>

<script>
import VueNextLevelScroll from 'vue-next-level-scroll';

export default Vue.extend({
    components: {
	VueNextLevelScroll
    },
});
</script>
```

**Comment by TheAlexLichter** [comment]
That's a limitation of `document.querySelector`.

You could define a custom scroll function though that'll find the element in the iframe, e.g. like in https://stackoverflow.com/questions/26630519/queryselector-for-web-elements-inside-iframe
